const gold="#F4C20D";
const page={maxWidth:1100,margin:"0 auto",padding:"0 20px"};
const button={display:"inline-flex",alignItems:"center",justifyContent:"center",minHeight:54,padding:"0 22px",borderRadius:10,fontWeight:900,fontSize:15,textDecoration:"none"};

export default function Home(){
  return <main style={{background:"#050505",minHeight:"100vh",color:"#fff",fontFamily:"Arial,sans-serif"}}>
    <nav style={{padding:"16px 20px",borderBottom:"1px solid #222",display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,flexWrap:"wrap",position:"sticky",top:0,zIndex:20,background:"rgba(5,5,5,.96)",backdropFilter:"blur(10px)"}}>
      <a href="/" style={{color:gold,fontWeight:900,textDecoration:"none",letterSpacing:1}}>GET CHA RIGHT</a>
      <div style={{display:"flex",gap:16,flexWrap:"wrap",fontSize:14}}><a href="/services" style={{color:"#ccc",textDecoration:"none"}}>Services</a><a href="/pricing" style={{color:"#ccc",textDecoration:"none"}}>Pricing</a><a href="/about" style={{color:"#ccc",textDecoration:"none"}}>About</a><a href="/personal-trainer-georgia" style={{color:"#ccc",textDecoration:"none"}}>Georgia Training</a><a href="/members" style={{color:gold,textDecoration:"none",fontWeight:800}}>Members</a></div>
    </nav>

    <section style={{background:"radial-gradient(circle at 75% 18%,rgba(244,194,13,.13),transparent 28rem),linear-gradient(180deg,#0a0a0a,#050505)",padding:"clamp(70px,10vw,125px) 20px 90px"}}>
      <div style={{...page}}>
        <div style={{maxWidth:850}}><p style={{color:gold,fontWeight:900,letterSpacing:2,fontSize:13,margin:0}}>PERSONAL TRAINING + ONLINE COACHING</p><h1 style={{fontSize:"clamp(48px,8vw,86px)",lineHeight:.92,letterSpacing:-3,margin:"20px 0"}}>GET STRONGER.<br/>MOVE BETTER.<br/>GET CHA RIGHT.</h1><p style={{maxWidth:740,color:"#d0d0d0",fontSize:"clamp(17px,2vw,21px)",lineHeight:1.65}}>Personalized coaching for adults who want to lose body fat, build muscle, get stronger, improve conditioning, move better, or finally get consistent.</p><p style={{fontSize:16,fontWeight:800,lineHeight:1.6}}>1-on-1 training in Villa Rica and the west Atlanta area. Online and hybrid coaching are available too.</p><div style={{display:"flex",gap:12,flexWrap:"wrap",marginTop:28}}><a href="/starter-kit" style={{...button,background:gold,color:"#050505"}}>TRY THE 3-DAY PREVIEW</a><a href="/services" style={{...button,background:"transparent",color:"#fff",border:"1px solid #444"}}>SEE SERVICES</a></div><p style={{color:"#777",marginTop:16,fontSize:13}}>Have questions? <a href="/contact" style={{color:"#fff",fontWeight:800}}>Talk directly with Que.</a></p></div>
      </div>
    </section>

    <section style={{...page,paddingTop:65,paddingBottom:65}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:16}}>{[["LOSE BODY FAT","Build a realistic training and nutrition routine you can actually maintain."],["BUILD STRENGTH","Learn how to train with purpose and progress instead of guessing."],["MOVE BETTER","Improve mobility, conditioning, and how your body feels day to day."],["STAY ACCOUNTABLE","Get coaching, check-ins, and adjustments when life gets busy."]].map(([t,d])=><article key={t} style={{background:"#111",border:"1px solid #292929",borderRadius:16,padding:23}}><div style={{color:gold,fontWeight:900,fontSize:12,letterSpacing:1.5}}>{t}</div><p style={{color:"#aaa",lineHeight:1.65,marginBottom:0}}>{d}</p></article>)}</div></section>

    <section style={{background:"#0d0d0d",padding:"75px 20px"}}><div style={{...page}}><div style={{maxWidth:850,margin:"0 auto",textAlign:"center"}}><p style={{color:gold,fontWeight:900,letterSpacing:2,fontSize:12}}>REAL COACHING. REAL EXPERIENCE.</p><h2 style={{fontSize:"clamp(34px,5vw,54px)",lineHeight:1,margin:"10px 0 18px"}}>You're not buying another random workout.</h2><p style={{color:"#aaa",fontSize:17,lineHeight:1.7,maxWidth:700,margin:"0 auto 24px"}}>You're getting a coach who helps you understand what to do, why you're doing it, and how to keep progressing.</p><a href="/about" style={{...button,background:"#fff",color:"#050505"}}>MEET COACH QUE</a></div></div></section>

    <section style={{...page,paddingTop:75,paddingBottom:75}}><p style={{color:gold,fontWeight:900,letterSpacing:2,fontSize:12,textAlign:"center"}}>CLIENT FEEDBACK</p><h2 style={{fontSize:"clamp(32px,5vw,48px)",textAlign:"center",margin:"8px 0 30px"}}>What clients say</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:16}}>{[["Kevonta Cropper","Amazing knowledge and expertise! atmosphere was wonderful as well. Highly recommend"],["Nolyt Ylrae","Laquince gone get you right. Great motivation and dedication"]].map(([n,t])=><blockquote key={n} style={{margin:0,background:"#111",border:"1px solid #292929",borderRadius:16,padding:24}}><div style={{color:gold,letterSpacing:2,marginBottom:12}}>★★★★★</div><p style={{color:"#ddd",lineHeight:1.7}}>“{t}”</p><footer style={{color:"#888",fontSize:13,fontWeight:800}}>{n} · Google Review</footer></blockquote>)}</div></section>

    <section style={{background:gold,color:"#050505",padding:"65px 20px",textAlign:"center"}}><div style={{...page}}><h2 style={{fontSize:"clamp(32px,5vw,52px)",margin:"0 0 12px"}}>Stop guessing. Start training with a plan.</h2><p style={{fontSize:17,maxWidth:650,margin:"0 auto 24px",lineHeight:1.6}}>Try the 3-day coaching preview and see how Get Cha Right can fit your goal and schedule.</p><a href="/starter-kit" style={{...button,background:"#050505",color:"#fff"}}>START MY 3-DAY PREVIEW →</a></div></section>
  </main>
}