export default function Testimonials() {
  const reviews=[
    {name:"Kevonta Cropper",text:"Amazing knowledge and expertise! atmosphere was wonderful as well. Highly recommend"},
    {name:"Nolyt Ylrae",text:"Laquince gone get you right. Great motivation and dedication"},
  ];
  const steps=[["Create Your Account","Start your Get Cha Right account and choose your coaching path."],["Complete Your Assessment","Tell me your goals, experience, equipment, and schedule."],["Get Your Program","Your training plan is built around your goal and coaching needs."],["Train & Track","Log workouts, nutrition, mobility work, and progress."],["Check In","Use check-ins so your plan can be adjusted as you progress."]];
  const card={background:"#111",border:"1px solid #2A2A2A",borderRadius:18,padding:24};
  return <>
    <section style={{padding:"75px 20px",background:"#0d0d0d",color:"#fff"}}><div style={{maxWidth:1100,margin:"0 auto"}}><p style={{color:"#F4C20D",fontWeight:900,letterSpacing:2,fontSize:12,textAlign:"center"}}>WHAT CLIENTS SAY</p><h2 style={{fontSize:"clamp(30px,4vw,44px)",margin:"8px 0 28px",textAlign:"center"}}>Client reviews</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:18}}>{reviews.map(review=><blockquote key={review.name} style={{...card,margin:0}}><div style={{color:"#F4C20D",letterSpacing:2,marginBottom:12}}>★★★★★</div><p style={{color:"#DDD",lineHeight:1.65,margin:"0 0 14px"}}>“{review.text}”</p><footer style={{color:"#999",fontSize:13,fontWeight:700}}>{review.name} · Google Review</footer></blockquote>)}</div></div></section>
    <section style={{padding:"75px 20px",background:"#050505",color:"#fff"}}><div style={{maxWidth:900,margin:"0 auto"}}><p style={{color:"#F4C20D",fontWeight:900,letterSpacing:2,fontSize:12,textAlign:"center"}}>SIMPLE FROM DAY ONE</p><h2 style={{fontSize:"clamp(34px,5vw,52px)",margin:"8px 0 38px",textAlign:"center"}}>How it works</h2><div style={{display:"grid",gap:12}}>{steps.map(([title,description],index)=><div key={title} style={{display:"grid",gridTemplateColumns:"52px 1fr",gap:16,alignItems:"start",background:"#111",padding:20,border:"1px solid #2A2A2A",borderRadius:12}}><div style={{width:44,height:44,borderRadius:"50%",background:"#F4C20D",color:"#050505",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900}}>{index+1}</div><div><h3 style={{margin:"2px 0 7px",fontSize:18}}>{title}</h3><p style={{margin:0,color:"#999",lineHeight:1.55,fontSize:14}}>{description}</p></div></div>)}</div></div></section>
  </>;
}