export const metadata={title:"Free 3-Day Coaching Preview | Get Cha Right Fitness",description:"Try Get Cha Right Fitness coaching free for 3 days. Choose your goal and see the type of workouts and coaching structure you can expect before purchasing a full program.",alternates:{canonical:"/starter-kit"}};
const goals=[
 ["LOSE WEIGHT / BODY FAT","Full-body training, cardio and core work designed to show how training can support a fat-loss goal."],
 ["BUILD MUSCLE","Upper-body, lower-body and full-body sessions that show how I structure muscle-building training."],
 ["GAIN HEALTHY WEIGHT & SIZE","Strength-focused workouts plus simple guidance on eating consistently enough to support your goal."],
 ["GET STRONGER","Three strength-focused sessions built around getting better at the major movement patterns."],
 ["IMPROVE CONDITIONING","A mix of full-body work and conditioning to show how we build fitness without making every workout the same."],
 ["MOVE BETTER / FEEL LESS STIFF","Lighter strength and movement sessions for people who want to move better and feel less stiff."],
 ["GET BACK INTO WORKING OUT","Beginner-friendly full-body sessions that help you restart without trying to do too much on Day 1."]
];
export default function StarterKit(){return <main style={{minHeight:"100vh",background:"#050505",color:"#fff",fontFamily:"Arial,sans-serif"}}><section style={{maxWidth:1000,margin:"0 auto",padding:"70px 20px"}}>
 <div style={{textAlign:"center"}}><p style={{color:"#F4C20D",fontWeight:900,letterSpacing:2}}>GET CHA RIGHT FITNESS</p><h1 style={{fontSize:"clamp(38px,7vw,70px)",lineHeight:1,margin:"0 0 22px",fontWeight:900}}>TRY MY COACHING<br/><span style={{color:"#F4C20D"}}>FREE FOR 3 DAYS</span></h1>
 <p style={{maxWidth:760,margin:"0 auto 18px",fontSize:20,lineHeight:1.6,color:"#ddd"}}>Tell me what you're trying to accomplish and I'll show you a simple 3-day workout preview based on your goal. It's a way to see how I structure training before you decide whether you want full coaching.</p>
 <p style={{fontWeight:800}}>No personal-training jargon. No guessing what you're signing up for.</p></div>
 <section style={{marginTop:45,background:"#111",border:"1px solid #333",borderRadius:18,padding:"28px clamp(18px,4vw,38px)"}}><h2 style={{marginTop:0}}>What are you actually getting?</h2><p style={{color:"#ccc",lineHeight:1.7}}>You'll get <strong style={{color:"#fff"}}>three workouts</strong> that show the type of coaching you can expect from Get Cha Right Fitness. The preview is based on the goal you choose, where you train, your experience, how much time you have, and how many days you can normally work out.</p>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:12,marginTop:22}}>{["3 workout sessions","About 20–60 min based on your answers","Home, gym or both","Goal-based training","A preview—not your full paid program"].map(x=><div key={x} style={{background:"#080808",padding:16,borderRadius:10,border:"1px solid #292929",color:"#ddd"}}>✓ {x}</div>)}</div></section>
 <h2 style={{textAlign:"center",fontSize:32,margin:"55px 0 10px"}}>CHOOSE YOUR GOAL</h2><p style={{textAlign:"center",color:"#aaa",marginBottom:25}}>Your 3-day preview changes depending on what you're trying to accomplish.</p>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:14}}>{goals.map(([t,d])=><div key={t} style={{background:"#111",border:"1px solid #292929",borderRadius:14,padding:22}}><h3 style={{color:"#F4C20D",fontSize:15}}>{t}</h3><p style={{color:"#bbb",lineHeight:1.6,marginBottom:0}}>{d}</p></div>)}</div>
 <section style={{textAlign:"center",marginTop:50,padding:30,background:"#111",border:"1px solid #F4C20D",borderRadius:16}}><h2 style={{marginTop:0}}>Ready to try it?</h2><p style={{color:"#ccc",lineHeight:1.6,maxWidth:650,margin:"0 auto 20px"}}>Tap the gold <strong>FREE 3-DAY PREVIEW</strong> button on this page. Choose your goal, training location, experience, available time and normal training frequency. Then enter your information to save your answers.</p><a href="/" style={{display:"inline-block",color:"#050505",background:"#F4C20D",padding:"14px 20px",borderRadius:10,textDecoration:"none",fontWeight:900}}>BACK TO GET CHA RIGHT FITNESS</a></section>
 <p style={{color:"#777",fontSize:13,maxWidth:760,margin:"40px auto 0",lineHeight:1.5,textAlign:"center"}}>The free preview is a general coaching sample based on the answers you select, not an individualized medical or exercise assessment. Full coaching includes a more complete onboarding process and ongoing adjustments.</p>
 </section></main>}
